﻿IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'Location')
BEGIN
	CREATE TABLE [dbo].[Location](
		[Id] [INT] IDENTITY(1,1) NOT NULL,
		[Name] [NVARCHAR](255) NOT NULL,
		[3BedHouseAverageSalePrice] [INT] NOT NULL,
		[3BedHouseAverageRentPrice] [INT] NOT NULL,
		[AveragePriceMortgage] [INT] NOT NULL,
		[MortgageToRent_DiffPc] [INT] NOT NULL,
		[MortgageToRent_DiffValue] [INT] NOT NULL, 
		[Date] [DATETIME] NOT NULL,
		CONSTRAINT [PK_Location] PRIMARY KEY CLUSTERED
		(
			[Id] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
		ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
END